 version: 2.1
 jobs:
   build:
     docker:
       - image: circleci/node:12.14.0
     steps:
       - run: yarn add request
       - run: cat package.json
       - run: ls -la
       - run: yarn install
       - run: yarn test
