 version: 2.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node


 jobs:
   build:
     branches:
       only:
         - feature/autopublish-to-npm
     docker:
       - image: circleci/node
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-npm-wee
          command: npm install
       - run:
           name: install-request-codecov
           command: npm install request codecov
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      test:
        - run:
           name: test
           command: npm test
        - run: 
           name: report-coverage
           command: npm run report-coverage t $CODECOV_TOKEN
        - store_artifacts:
           path: coverage
           prefix: coverage