 version: 2.0
 jobs:
   build:
     branches:
       only:
         - master
     docker:
       - image: circleci/node:12.14.0
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - run:
          name: install-npm-wee
          command: npm install
       - run:
           name: install-request-codecov
           command: npm install request codecov
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: test
          command: npm test
       - run: 
          name: report-coverage
          command: npm run report-coverage t $CODECOV_TOKEN
       - store_artifacts: 
          path: test-results.xml
          prefix: tests
       - store_artifacts:
          path: coverage
          prefix: coverage