 version: 2.1
 jobs:
   build:
     docker:
       - image: circleci/node:12.14.0
     steps:
       - run: node -e "console.log(require('request'))"
       - run: ls -la
       - run: npm install
       - run: npm run test
